networks:
  mongo:

services:
  heyform:
    image: workcenterma/heyforms
    restart: always
    volumes:
      - ./assets:/app/static/upload
    depends_on:
      - mongo
    ports:
      - "9513:8000"
    environment:
      APP_HOMEPAGE_URL: http://127.0.0.1:9513
      SESSION_KEY: key1
      FORM_ENCRYPTION_KEY: key2
      MONGO_URI: "mongodb://mongo:27017/heyform"
      REDIS_HOST:
      REDIS_PORT:
      REDIS_PASSWORD:

  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
